package cbstudios.coffeebreak.model.toDoDataModule.toDoList;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IListTask.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//


public interface IListTask {
    public void getters();

    public void setters();
}
