package cbstudios.coffeebreak.model.tododatamodule.todolist;

//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.toDoList.Task.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 
//
//
public class Task implements ITask {
    private String name;
    private boolean checked;

    public Task(){
        checked = false;
    }
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public boolean isChecked() {
        return checked;
    }

    public void toggleChecked() {
        setChecked(!isChecked());
    }

    public void setChecked(boolean value) {
        checked = value;
    }
}
