package cbstudios.coffeebreak.model.toDoDataModule.toDoList;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.toDoList.TimeCategory.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 
//
//


import cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date;
import cbstudios.coffeebreak.model.toDoDataModule.categoryList.ITimeCategory;

public class TimeCategory implements ITimeCategory {
	private Date time;
	public void getters();
	public void setters();
	public boolean isInIntervall(Object Date);
}
