package cbstudios.coffeebreak.model.tododatamodule.todolist;//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.toDoList.TODOList.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 
//
//


public class TODOList {
    private ITaskFactory taskFactory;
    private List<IAdvancedTask> tasks;

    private void initComponents() {

    }
}
