//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CategoryList.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public class CategoryList implements ICategoryList {
	private ICategoryFactory categoryFactory;
	private List<LabelCategory> labelCategories;
	private List<TimeCategory> timeCategories;
	public void getters();
	public void setters();
	public void addLabelCategory(Object String);
	public void removeLabelCategory(Object ILabelCategory);
	public void removeLabelCategory(Object String);
	public List<ITimeCategory> getTimeCategories();
	public void initTimeCategories();
}
