//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : IAdvancedTask.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public interface IAdvancedTask {
	public void setters();
	public void getters();
	public void isChecked();
	public void toggleChecked();
	public void setChecked(Object boolean);
}
