//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ICategoryList.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public interface ICategoryList {
	public void getters();
	public void setters();
	public void addLabelCategory(Object String);
	public void removeLabelCategory(Object ILabelCategory);
	public void removeLabelCategory(Object String);
	public List<ITimeCategory> getTimeCategories();
	public void initTimeCategories();
}
