//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ITask.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public interface ITask {
	public String getName();
	public void setName(Object String);
	public void isChecked();
	public void toggleChecked();
	public void setChecked(Object boolean);
}
