//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ITimeCategory.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public interface ITimeCategory {
	public void getters();
	public void setters();
	public boolean isInIntervall(Object Date);
}
