//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : LabelCategory.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public class LabelCategory implements ILabelCategory {
	private String name;
	private Color color;
}
