//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ListTask.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public class ListTask extends AdvancedTask implements IListTask {
	private List<ITask> subTasks;
	public void setters();
	public void getters();
	public void isChecked();
	public void toggleChecked();
	public void setChecked(Object boolean);
	public void getters();
	public void setters();
}
