//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TaskFactory.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public class TaskFactory implements ITaskFactory {
	public void createTask() {
	
	}
	
	public void createTask();
}
