//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Task.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public class Task implements ITask {
	private String name;
	private boolean checked;
	public String getName();
	public void setName(Object String);
	public void isChecked();
	public void toggleChecked();
	public void setChecked(Object boolean);
}
