//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TimeCategory.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public class TimeCategory implements ITimeCategory {
	private Date time;
	public void getters();
	public void setters();
	public boolean isInIntervall(Object Date);
}
