//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TODOList.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public class TODOList {
	private ITaskFactory taskFactory;
	private List<IAdvancedTask> tasks;
	private void initComponents() {
	
	}
}
