//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : TODODataModule.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//




public class TODODataModule {
	private ICategoryList categoryList;
	private ToDoList toDoList;
	private void initComponents() {
	
	}
}
