package cbstudios.coffeebreak.model.toDoDataModule.categoryList;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.categoryList.CategoryList.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 
//
//


import cbstudios.coffeebreak.model.toDoDataModule.toDoList.TimeCategory;

public class CategoryList implements ICategoryList {
	private ICategoryFactory categoryFactory;
	private List<LabelCategory> labelCategories;
	private List<TimeCategory> timeCategories;
	public void getters();
	public void setters();
	public void addLabelCategory(Object String);
	public void removeLabelCategory(Object ILabelCategory);
	public void removeLabelCategory(Object String);
	public List<ITimeCategory> getTimeCategories();
	public void initTimeCategories();
}
