package cbstudios.coffeebreak.model.toDoDataModule.categoryList;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.categoryList.CategoryFactory.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 
//
//


public class CategoryFactory implements ICategoryFactory {
    public ILabelCategory createLabelCategory();

    public ILabelCategory createLabelCategory(Object String);

    public ITimeCategory createMultipleDayCategory();

    public ITimeCategory createSingleDayCategory();
}
