package cbstudios.coffeebreak.model.tododatamodule.categorylist;////
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ILabelCategory.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//


/**
 * An interface for the labelCategory
 */
public interface ILabelCategory extends ICategory {
    /**
     * @return the color of the labelCategory
     */
    String getColor();

    /**
     * Sets a new Color to a labelCategory
     *
     * @param color is the new color of a labelCategory
     */
    void setColor(String color);
}