package cbstudios.coffeebreak.model.tododatamodule.categorylist;////
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ILabelCategory.java
//  @ Date : 03/04/2017
//  @ Author : 
//
//


import android.graphics.Color;

public interface ILabelCategory {
    public String getName();

    public void setName(String name);

    public Color getColor();

    public void setColor(Color color);
}