package cbstudios.coffeebreak.model.toDoDataModule.categoryList;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.categoryList.LabelCategory.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 
//
//




public class LabelCategory implements ILabelCategory {
	private String name;
	private Color color;
}
