package cbstudios.coffeebreak.model.tododatamodule.categorylist;////
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.categoryList.MultipleDayTimeCategory.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 
//
//


import java.util.GregorianCalendar;

public class MultipleDayTimeCategory implements ITimeCategory {

    private String name;
    private GregorianCalendar time;


    public void setName(String name) {
        this.name = name;
    }

    public GregorianCalendar getTime() {
        return time;
    }

    public void setTime(GregorianCalendar time) {
        this.time = time;
    }


    public boolean isInIntervall(GregorianCalendar taskTime){
        return false;
    }
}
