package cbstudios.coffeebreak.model.tododatamodule.categorylist;////
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.categoryList.MultipleDayTimeCategory.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 
//
//


public class MultipleDayTimeCategory implements ITimeCategory {
    private String name;
    private Date time;

    public void getters();

    public void setters();

    public boolean isInIntervall(Object Date);
}
