package cbstudios.coffeebreak.model.tododatamodule.categorylist;//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.toDoList.TimeCategory.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author :

import cbstudios.coffeebreak.model.tododatamodule.categorylist.ITimeCategory;

import java.util.Calendar;

public class TimeCategory implements ITimeCategory {
    private Calendar time;

    public boolean isInIntervall(Object Date);
}
