package cbstudios.coffeebreak.model.tododatamodule;
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.TODODataModule.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 


import cbstudios.coffeebreak.model.tododatamodule.categorylist.CategoryList;
import cbstudios.coffeebreak.model.tododatamodule.categorylist.ICategoryList;
import cbstudios.coffeebreak.model.tododatamodule.todolist.TODOList;

public class TODODataModule {
    private ICategoryList categoryList;
    private TODOList todoList;

    public TODODataModule(){
        categoryList = new CategoryList();
        todoList = new TODOList();
    }
    private void initComponents() {

    }
}
