package cbstudios.coffeebreak.model.toDoDataModule;//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : cbstudios.coffeebreak.model.toDoDataModule.TODODataModule.java
//  @ cbstudios.coffeebreak.model.toDoDataModule.categoryList.Date : 03/04/2017
//  @ Author : 
//
//


import cbstudios.coffeebreak.model.toDoDataModule.categoryList.ICategoryList;

public class TODODataModule {
	private ICategoryList categoryList;
	private ToDoList toDoList;
	private void initComponents() {
	
	}
}
